name: Test echo
on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:
      inputs:
        yeet:
          description: 'you yeet?'
          required: false
          default: 'true'
jobs:
  greet:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
  greet2:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting 2
      run: echo "Hello2 ${{ github.event.inputs.name }}"

