name: Test echo
on:
  push:
    branches:
      - main
  workflow_dispatch:
      inputs:
        yeet:
          description: 'you yeet?'
          required: false
          default: 'true'
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
